name: ci-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: simple_bank
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.x'

    - name: Install golang-migrate
      run: |
        curl -L https://github.com/golang-migrate/migrate/releases/download/v4.19.0/migrate.linux-amd64.tar.gz | tar xvz
        sudo mv migrate /usr/local/bin/
        which migrate

    - name: Create app.env from secrets
      run: |
        echo "DB_DRIVER=postgres" >> app.env
        echo "DB_SOURCE=${{ secrets.DB_SOURCE }}" >> app.env
        echo "SERVER_ADDRESS=0.0.0.0:8080" >> app.env
        echo "TOKEN_SYMMETRIC_KEY=${{ secrets.TOKEN_SYMMETRIC_KEY }}" >> app.env
        echo "ACCESS_TOKEN_DURATION=15m" >> app.env
        echo "REFRESH_TOKEN_DURATION=24h" >> app.env

    - name: Run migrations
      run: make migrateup

    - name: Run tests
      run: make test
